package me.mircea.cravecart.deliverytracking.orderlocation;

import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.codec.ServerSentEvent;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;

import java.time.Duration;
import java.util.Objects;

@RestController
@RequestMapping("/order-locations")
@RequiredArgsConstructor
public class OrderSseController {
    private final OrderLocationPublisher orderLocationPublisher;

    @GetMapping(path = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<ServerSentEvent<OrderLocationMessage>> streamOrderLocations(
            @RequestParam("order-id") Long orderId
    ) {
        return orderLocationPublisher.getFlux()
                .filter(orderLocationMessage -> Objects.equals(orderLocationMessage.orderId(), orderId))
                .sample(Duration.ofSeconds(5))
                .map(orderLocationMessage -> ServerSentEvent.<OrderLocationMessage>builder()
                        .id(String.valueOf(orderLocationMessage.moment().toEpochMilli())) // todo: use a snowflake ID generated by the server
                        .event("order-location-update")
                        .data(orderLocationMessage)
                        .build()
                );
    }
}
